# -*- coding: utf-8 -*-
"""Temporal_Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10piif3dRbPPnEK7Z--bLjCHGhttHRE7O

# **Maestría en Inteligencia Artificial y Analítica de Datos**

Asignatura: *Programación para Analítica Descriptiva y Predictiva*

* Semestre: Enero-Junio 2026
* Profesor: Dr. Vicente García Jiménez
* Alumno: Ricardo Solano Monje
* Matrícula: 266221
* Unidad 2.
* Prácticas: 18, Limpieza y Transformación de Datos Temporales.
* Objetivo de la práctica: El objetivo de esta actividad es que los estudiantes practiquen los temas vistos de limpieza y transformación de datos temporales, utilizando un dataset particular con Pandas en Python.
* Realizado por: Ricardo Solano Monje
"""

import pandas as pd
from IPython.display import display, Markdown
from datetime import date
from datetime import datetime
from zoneinfo import ZoneInfo

today = date.today()
time_zone = ZoneInfo('America/Ciudad_Juarez')
current_time_aware = datetime.now(time_zone)

display(Markdown(f"### Current time in Cd. Juárez, Chih.: {current_time_aware.strftime('%H:%M:%S')}"))
formatted_date = today.strftime("%B %d, %Y")
display(Markdown(f"### Today's date: {formatted_date}"))

from IPython.display import display, Markdown
def eprint(markdown_text) -> None:
    display(Markdown("### "+markdown_text))
    return None

"""# Ejercicio 01:Tipo de Datos Correcto

* Carga el conjunto de datos airdata.csv,
* Verifica que cada columna tenga el tipo de datos correcto,
* Si una columna de tipo temporal no está en el tipo de correcto realiza la conversión,
* Usa dtypes para mostrar que cada columna está en el tipo de datos correcto (principalmente la que contiene datos temporales),
* Imprime las primeras tres líneas.

### Hint:
The pandas.to_datetime() function converts a scalar, array-like, Series, or DataFrame into a pandas datetime object (specifically a datetime64[ns] dtype or a Timestamp object). This is essential for performing time-series operations such as filtering by date, calculating time differences, or extracting components like the year or month.
"""

import pandas as pd

def load_data(file_path) -> pd.DataFrame | None:
    """
    Load the airdata.csv dataset
    """
    try:
      df = pd.read_csv(file_path)
      print(f"Data loaded successfully. Shape: {df.shape}")
      return df
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        pass #return None

def check_and_convert_dtypes(df) -> pd.DataFrame | None:
    """
    Verify and convert columns to correct data types,
    with special attention to temporal data
    """
    # Display original data types
    print("-"*50)
    print("Original data types:")
    print("-"*50)
    print(df.dtypes)
   # print("\n" + "="*50 + "\n")

    # Make a copy to avoid warnings
    df_converted = df.copy()

    # Even though we know which is the datetime column, let's try guess the column having such a name.
    # Identify and convert temporal columns
    # Checking Common temporal column names to check
    temporal_keywords = ['date', 'time', 'datetime', 'timestamp', 'day', 'month', 'year']

    for col in df_converted.columns:
        col_lower = col.lower()

        # Check if column might contain temporal data
        if any(keyword in col_lower for keyword in temporal_keywords):
            try:
                # Attempt to convert to datetime, from 1/1/2020 0:00 to 2020-01-01 00:00:00
                col_old_type=df_converted[col].dtype #save current series dtype
                df_converted[col] = pd.to_datetime(df_converted[col]) # the whole Series is converted.
                print(f">>>>> Converted {col} of dtype {col_old_type} to datetime of dtype {df_converted[col].dtype}<<<<<")
            except (ValueError, TypeError):
                # If conversion fails, keep original and notify
                print(f"Could not convert '{col}' to datetime, keeping original")

        # Check for numeric columns that might be stored as objects
        elif df_converted[col].dtype == 'object':
            try:
                # Try to convert to numeric
                df_converted[col] = pd.to_numeric(df_converted[col])
                print(f"Converted '{col}' to numeric")
            except (ValueError, TypeError):
                # Keep as object if conversion fails
                pass

    return df_converted

def main() -> tuple[pd.DataFrame | None, pd.DataFrame | None]:
    # print("-"*50)
    # print("\n" + "="*50 + "\n")
    # print("="*50 + "\n")
    """
    Main function as controller of the data cleaning process
    """
    # File path
    file_path = 'drive/MyDrive/ClassFiles/airdata.csv' # do not forget to remove "./" for running in colab

    # Step 1: Load the data
    print("="*50)

    eprint("Step 1: Loading data...")
    print("="*50 + "\n")

    df = load_data(file_path)
    print("-"*50)
    eprint("Displaying first three rows of original dataframe:")
    print("-"*50)
    print(df.head(3))

    if df is not None:
        #print("\n" + "="*50 + "\n")

        # Step 2-3: Check and convert data types
        print("="*50)
        eprint("Step 2-3: Checking and converting data types...")
        print("="*50 + "\n")
        df_clean = check_and_convert_dtypes(df)

        # Step 4: Show final data types
        print("="*50)
        eprint("Step 4: Showing final data types after conversion:")
        print("="*50 + "\n")
        print(df_clean.dtypes)


        # Step 5: Print first three lines
        print("="*50)
        eprint("Step 5: Displaying first three rows of verified type data:")
        print("="*50 + "\n")
        print(df_clean.head(3))

        return df, df_clean
    else:
        print("Failed to load data. Exiting.")
        pass # return None

# Execute the main function
if __name__ == "__main__":
    df,cleaned_data = main()
    print("="*80)

"""# Ejercicio 02: Extraer componentes de fecha y tiempo

* De la columna 'DateTime' extrae el año, mes, día y hora,
* Crea una nueva columna para cada componente que extraes,
* Imprime las primeras tres líneas del dataframe que ahora deberá tener 4 nuevas columnas.

### Hint:

The pandas.Series.dt.year attribute is used to extract the year as an integer value from a Series containing datetime objects.
This attribute is accessed via the .dt accessor, which provides a collection of datetime properties and methods. Same applies for month, day and time.
"""

#from typing import Optional
import pandas as pd
from IPython.display import display, Markdown

def load_data(file_path: str) -> pd.DataFrame | None:
    """
    Load the airdata.csv dataset

    Args:
        file_path: Path to the CSV file

    Returns:
        DataFrame if successful, None (pass) if file not found
    """
    try:
        df = pd.read_csv(file_path)
        print(f"Data loaded successfully. Shape: {df.shape}")
        return df
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        pass #return None

def extract_date_components(df) -> pd.DataFrame:
    """
    Extract year, month, day, and time from the DateTime column
    """
    # Make a copy to avoid modifying the original
    df_extracted = df.copy()

    # Check if DateTime column exists
    if 'DateTime' in df_extracted.columns:
        # Convert to datetime if not already, because exercises are encapsulated.
        df_extracted['DateTime'] = pd.to_datetime(df_extracted['DateTime'])

        # Extract components: year, month, day and time from Series/column 'DateTime'
        df_extracted['Year'] = df_extracted['DateTime'].dt.year
        df_extracted['Month'] = df_extracted['DateTime'].dt.month
        df_extracted['Day'] = df_extracted['DateTime'].dt.day
        df_extracted['Time'] = df_extracted['DateTime'].dt.time

        print("Extracted year, month, day, and time from DateTime column")
    else:
        display(Markdown("## Error: DateTime column not found in the dataset"))

    return df_extracted

def main() -> tuple[pd.DataFrame | None, pd.DataFrame | None]:
    """
    Main function to orchestrate the data extraction process
    """
    print("="*50)
    print("EXTRACTING DATE AND TIME COMPONENTS")
    print("="*50)

    # Step 1: Load the data
    print("Loading data...")
    file_path = 'drive/MyDrive/ClassFiles/airdata.csv'
    df = load_data(file_path)

    if df is not None:
        # Display original columns
        eprint("Original columns: ")
        print(f"{list(df.columns)}")
        print(f"Original shape: {df.shape}")

        # Step 1 & 2: Extract date components and create new columns
        print("-"*50)
        eprint("Step 1-2: Extracting date components and adding new columns...")
        print("-"*50)
        df_clean = extract_date_components(df)

        # Display new columns
        new_columns = ['Year', 'Month', 'Day', 'Time']
        print(f"\nNew columns added: {new_columns}")
        print(f"New shape: {df_clean.shape}")

        # Step 3: Print first three lines
        print("\n" + "="*50)
        eprint("Step 3: FIRST THREE ROWS (with new columns)")
        print("="*50)
        print(df_clean.head(3))

        # Return both original and modified dataframes for being able to be used in other cells
        return df, df_clean
    else:
        print("Failed to load data. Exiting.")
        pass #return None, None

# Execute the main function and capture both dataframes
if __name__ == "__main__":
    df_original, df_with_components = main()
    print("="*80)

"""# Ejercicio 03: Aritmética - Suma de Intervalos (timedelta)

* Suma 10 días, 7 horas y 15 minutos a cada elemento de la columna 'DateTime'.
* Guarda el resultado en una nueva columna y agrega al dataframe.
* Imprime la columna 'DateTime' y la columna que resulta de sumar 10 días, 7 horas y 15 minutos.

### Hint:

The timedelta(days=0, seconds=0, microseconds=0, milliseconds=0, minutes=0, hours=0, weeks=0) function in Python's datetime module is used to represent a duration—the difference between two date or time instances. It is essential for date arithmetic, *allowing you to calculate past or future dates by **adding or subtracting** specific time intervals*.
"""

import pandas as pd
from datetime import timedelta

def load_data(file_path) -> tuple[pd.DataFrame | None]:
    """
    Load the airdata.csv dataset
    """
    try:
        df = pd.read_csv(file_path)
        print(f"Data loaded successfully. Shape: {df.shape}")
        return df
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        pass #return None

def ensure_datetime_column(df, column_name='DateTime'):
    """
    Ensure the DateTime column is in datetime format
    """
    df_copy = df.copy()
    # check if datetime does exist in any column
    if column_name in df_copy.columns:
        df_copy[column_name] = pd.to_datetime(df_copy[column_name])
        print(f"✓ '{column_name}' column converted to datetime format")
    else:
        print(f"✗ '{column_name}' column not found")

    return df_copy

def add_time_interval(df, datetime_col='DateTime', days=10, hours=7, minutes=15) -> pd.DataFrame:
    """
    Add a time interval to each element of the DateTime column
    """
    # Create a copy to avoid modifying the original
    df_result = df.copy()

    # Create timedelta
    time_to_add = timedelta(days=days, hours=hours, minutes=minutes)

    # Add the interval to each datetime element
    df_result['DateTime_Plus_Interval'] = df_result[datetime_col] + time_to_add #time can be added.

    print(f"✓ Added {days} days, {hours} hours, and {minutes} minutes to each datetime")
    print(f"  Interval: {time_to_add}")

    return df_result

def main() -> tuple[pd.DataFrame | None, pd.DataFrame | None]:
    """
    Main function to orchestrate the timedelta arithmetic
    """
    print("="*60)
    eprint("ARITHMETIC - SUM OF INTERVALS (TIMEDELTA)")
    print("="*60)

    # Step 1: Load the data
    print("\nLoading data...")
    file_path = 'drive/MyDrive/ClassFiles/airdata.csv'
    df_original = load_data(file_path)

    if df_original is not None:
        # Display basic info
        print(f"\nDataset info:")
        print(f"  - Rows: {df_original.shape[0]}")
        print(f"  - Columns: {df_original.shape[1]}")

        # Ensure DateTime column is in datetime format
        print("\nEnsuring DateTime column is in correct format...")
        df_with_datetime = ensure_datetime_column(df_original)

        # Show first few DateTime values
        #print(f"\nFirst 3 DateTime values:")
        #print(df_with_datetime['DateTime'].head(3))

        # Step 2 & 3: Add interval and create new column
        eprint("Step 1: Adding 10 days, 7 hours, and 15 minutes to DateTime")
        df_result = add_time_interval(df_with_datetime, days=10, hours=7, minutes=15)
        eprint("Step 2: Saving into new column -> DateTime_Plus_Interval")
        print(f"  - Columns: {df_result.info()}")

        # Step 4: Print the DateTime column and the new column
        print("\n" + "="*60)
        eprint("Step 3: Original column DateTime vs new column Datetime_Plus_Interval")
        print("="*60)

        # display datetime old and new columns
        print(df_result[['DateTime','DateTime_Plus_Interval']].head(6))

        # Show the difference calculation
        print("\n" + "="*40)
        print("VERIFICATION - Calculate the difference:")
        print("="*40)

        # Calculate the actual difference to verify
        sample_diff = df_result['DateTime_Plus_Interval'].iloc[0] - df_result['DateTime'].iloc[0]
        print(f"Difference for first row: {sample_diff}")
        print(f"Equallying: {sample_diff.days} days, {sample_diff.seconds//3600} hours, {(sample_diff.seconds//60)%60} minutes")

        # Return both original and modified dataframes
        return df_original, df_result
    else:
        print("Failed to load data. Exiting.")
        pass #return None, None

# Execute the main function and capture both dataframes

if __name__ == "__main__":
    df_original, df_with_interval = main()
    print("="*80)

"""# Ejercicio 04: Timestamp

* Convierte la columna 'DateTime' la cual tiene un formato de fecha legible a timestamp Unix,
* Guarda el resultado en una nueva columna,
* Imprime las primeras tres filas de  la columna 'DateTime' y la columna que representa dicha fecha en timestamp Unix

### Hints:

* The unix time stamp is a way to track time as a running total of seconds. This count starts at the Unix Epoch on January 1st, 1970 at UTC.
* The pd.Timestamp() function is the pandas equivalent of Python's datetime.datetime object and represents a single point in time. It is a core component for working with time-series data in pandas and is largely interchangeable with the standard Python datetime object in most cases.

Precision: Pandas internally represents timestamps with nanosecond precision, which is higher than Python's standard datetime.

* pd.Timedelta('1s') creates a pandas Timedelta object representing a duration of one second.

Functionality: It can be used for arithmetic operations, such as adding to or subtracting from a pandas Timestamp or Series.
"""

import pandas as pd

def load_data(file_path) -> pd.DataFrame | None:
    """Load CSV dataset."""
    return pd.read_csv(file_path)

def convert_to_unix_timestamp(df):
    """Adding a UnixTimestamp column converted from DateTime."""
    df_clean = df.copy()
    unix_timestamp=(pd.to_datetime(df_clean['DateTime']) - pd.Timestamp("1970-01-01"))// pd.Timedelta('1s')
    # Calculate seconds since epoch
    df_clean['UnixTimestamp'] = (
        pd.to_datetime(df_clean['DateTime']) - pd.Timestamp("1970-01-01")
    ) // pd.Timedelta('1s') # to integer division to convert from nano seconds to seconds


    # Ensure strict integer type (pandas division often returns float)
    df_clean['UnixTimestamp'] = df_clean['UnixTimestamp'].astype('int64')
    eprint("Step 2: Saving unix time stamp conversion in new column UnixTimestamp: ")
    print(f"{df_clean['UnixTimestamp'].info()}")
    return df_clean

def main() -> tuple[pd.DataFrame | None, pd.DataFrame | None]:

    """Main execution: load, convert, display, return dataframes."""
    df = load_data('drive/MyDrive/ClassFiles/airdata.csv')
    eprint("Step 1: Conversion from DateTime to Unix Timestamp, step by step")
    #print("Converting step by step...")
    datetime_row_0=pd.to_datetime(df['DateTime'].loc[0])
    datetime_unix_epoch=pd.Timestamp("1970-01-01")
    timedelta=pd.to_datetime(df['DateTime'].loc[0]) - pd.Timestamp("1970-01-01")
    print(f"DateTime from row 0 :")
    print(f"Timestamp({pd.to_datetime(df['DateTime'].loc[0])})")
    print(f"Timestamp of 1970-01-01 :")
    print(f"Timestamp({pd.Timestamp("1970-01-01")})")
    print(f"TimeDelta= Timestamp({pd.to_datetime(df['DateTime'].loc[0])}) - Timestamp({pd.Timestamp("1970-01-01")})=")
    print(f"TimeDelta= TimeDelta({timedelta})")
    print(f"TimeDelta value = {timedelta.value} giving in nanoseconds")
    print(f"Unix Timestamp given in seconds: {timedelta// pd.Timedelta('1s')}")
    df_clean = convert_to_unix_timestamp(df)


    # Verification
    # Check conversion for the first 3 rows
    for i in range(3):
        original_dt = pd.to_datetime(df_clean['DateTime'].iloc[i])
        recovered_dt = pd.to_datetime(df_clean['UnixTimestamp'].iloc[i], unit='s')
        if original_dt != recovered_dt:
            print(f"Error at row {i}: {original_dt} != {recovered_dt}")
        else:
            pass # Silent success
    print("="*40)
    print("The round-trip verification was successfully passed for the first 3 rows.")
    print("="*40)

     # Display first 3 rows
    eprint(" Step 3: Displaying the old DateTime column & the new UnixTimestap column")
    print(df_clean[['DateTime', 'UnixTimestamp']].head(3).to_string(index=False))
    return df, df_clean

if __name__ == "__main__":
    df, df_clean = main()
    print("="*80)

"""# Ejercicio 05: Filtrado de Fechas

* Utiliza la columna 'DateTime' y Filtra aquellas fechas que son mayores a 2020-11-01
* Imprime el resultado

### Hints:

Chronological Ordering:
* Pandas understands that '2020-11-02' is later than '2020-11-01'. So, once a bad form datetime is properly converted into a proper Pandas datetime Timestamp object datetime64[ns] using *pd.to_datetime(df['DateTime'])*, Pandas is able to perform chronological comparisons rather than alphabetical string comparisons.
* The function *pd.to_datetime(df['DateTime'])* converts the column from a string (object) data type to a datetime64 dtype.
* Once converted, Pandas understands which entries of df['DateTime'] are greater than '2020-11-01'. So, Pandas compares the entire Series of converted dates against the timestamp cast of the scalar string '2020-11-01' in a single vectorized operation.
"""

import pandas as pd

def load_data(file_path) -> pd.DataFrame:
    """Load the CSV dataset."""
    return pd.read_csv(file_path)

def filter_dates(df) -> pd.DataFrame:
    """Filter dataframe for dates greater than 2020-11-01."""
    df_filtered = df.copy()
    # Convert DateTime column to datetime for proper comparison
    df_filtered['DateTime'] = pd.to_datetime(df_filtered['DateTime'])
    # Filter for dates > 2020-11-01
    df_filtered = df_filtered[df_filtered['DateTime'] > '2020-11-01']
    return df_filtered

def main() -> pd.DataFrame | pd.DataFrame :
    """Main function: load, filter, print, return dataframes."""
    path = 'drive/MyDrive/ClassFiles/airdata.csv'

    # 1. Load dataset
    df = load_data(path)

    print("="*40)
    eprint(f" Number of rows being greater than 2020-11-01 : {(pd.to_datetime(df['DateTime']) > '2020-11-01').value_counts().get(True, 0)}")
    print("="*40)
    # 2. Filter for dates > 2020-11-01
    print("-"*40)
    print("Step 1: Filtering dates > 2020-11-01...")
    print("-"*40)
    df_filtered = filter_dates(df)

    # 3. Print the result
    print("="*40)
    eprint("Step 2: Printing filter dataframe ")
    print("="*40)
    print(df_filtered)

    # 4. Return original and filtered dataframes
    return df, df_filtered

if __name__ == "__main__":
    df, df_filtered = main()
    print("="*80)